# DO NOT COMMIT TO GITHUB AFTER SETUP
version: '3.8'

services:
  db:
    image: mysql:8.0
    restart: always
    ports:
      - 3307:3306
    volumes:
      - db:/var/lib/mysql
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      - MYSQL_DATABASE= # insert your own db name
      - MYSQL_ROOT_PASSWORD= #insert your own db password

volumes:
  db:
    driver: local
